name: CI

on:

  schedule:
    - cron: '0 5,19 * * *'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - uses: browser-actions/setup-chrome@latest

      - name: Build with Maven
        run: mvn clean test -DsuiteFile='GKTestSuite.xml'

      - name: Deploy report
        uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./src/test/reports
